user added
MoyaFausto/Challenge-Elections-Dami pull request #1
Opened 2020-01-23 18:39 UTC by damiTacconi

2020-01-23 18:59 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controller/UserController.java
> +    private final String USER_NOT_FOUND = "The user was not found";
Esto podria estar en una clase ErrorMessage y pones todos los errores ahi.

2020-01-23 18:59 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controller/UserController.java
> +import org.springframework.web.bind.annotation.*;
Fijate de no tener wildcard import, desactivalos desde el IDE

2020-01-23 18:59 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controller/UserController.java
> +    }
No deberías estar devolviendo un List de User, conviene mas devolver algo asi:
`{
       "users" : [ este seria el array de user ]
}`

2020-01-23 18:59 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controller/UserController.java
> +    }
Cuando lo leas preguntame y te explico por qué

2020-01-23 18:59 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controller/UserController.java
> +@RequestMapping("api/users")
Si todos van a tener un prefijo /api podes setearselo por defecto en el application.properties

2020-01-23 18:59 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controller/UserController.java
> +        return this.userService.save(user);
Para mejor legibilidad, siempre conviene antes del return dejar un espacio

2020-01-23 18:59 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controller/UserController.java
> +        return this.userService.save(user);
Lo mismo en todos los métodos de abajo

2020-01-23 18:59 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controller/UserController.java
> +    public User findById(@PathVariable("id") int id){
Intenta usar los Wrappers Integer, Long, etc

2020-01-23 18:59 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controller/UserController.java
> +               .orElseThrow(() -> new HttpClientErrorException(HttpStatus.BAD_REQUEST, this.USER_NOT_FOUND));
Esto debería estar pasando en el service

2020-01-23 18:59 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controller/UserController.java
> +               .orElseThrow(() -> new HttpClientErrorException(HttpStatus.BAD_REQUEST, this.USER_NOT_FOUND));
Lo mismo abajo

2020-01-23 19:00 UTC, damiTacconi commented on src/main/java/net/avalith/elections/controller/UserController.java
> +    private final String USER_NOT_FOUND = "The user was not found";
dale dale , ahora lo hago .

2020-01-23 19:03 UTC, MatiasTassara requested changes

2020-01-23 19:03 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/model/User.java
> +    @GeneratedValue
el id no tiene que ser autogenerado sino un UUID

2020-01-23 19:03 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/model/User.java
> +    @NotNull
le podrias agregar un mensaje en caso que se mande null

2020-01-23 19:03 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/service/UserService.java
> +    public Optional<User> findById(int id){
no deberias retornar un optional sino un user. Busca como "desenvolver" el optional. Y en caso de no encontrar tirar una exepcion

2020-01-23 19:03 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/service/UserService.java
> +        Optional<User> optionalUser = this.userJpaRepository.findById(id);
aca seria un user si arreglas lo de arrriba

2020-01-23 19:03 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/service/UserService.java
> +        Optional<User> optionalUser = this.userJpaRepository.findById(id);
igual que los anteriores

2020-01-23 19:03 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/service/UserService.java
> +            User oldUser = optionalUser.get();
al tirar una exepcion al no encontrar un user por su id en su respectivo metodo, te ahorras esta comprobacion y podes setearle los valores directamente

2020-01-23 19:03 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/service/UserService.java
> +            this.userJpaRepository.delete(optionalUser.get());
al validar en el find no haria falta la comprobacion aca

2020-01-23 19:04 UTC, ghost requested changes

2020-01-23 19:04 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/repository/UserJpaRepository.java
> +public interface UserJpaRepository extends JpaRepository<User , Integer> {
Dejalo como UserRepository

2020-01-23 19:04 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/service/UserService.java
> +    }
Dos returns quedan medio fuleros

2020-01-23 19:04 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/model/User.java
> +    private int dni;
El dni debe ser unico por usuario.

2020-01-23 19:04 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/model/User.java
> +@ToString
Creo que en el `@Data` ya te viene el `.toString()`

2020-01-24 01:48 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controller/UserController.java
> +@RequestMapping("/users")
`"/user"`

2020-01-24 01:48 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/model/User.java
> +    private UUID id;
Esto funciona? Sino manejalo como String, mas fácil

2020-01-24 01:48 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/service/UserService.java
> +    public void update(User user , Integer id){
No estaba en el ticket, pero no pasa nada. Devolvé el Usuario modificado.

2020-01-24 12:20 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User , Integer> {
en vez de integer , iria el tipo de dato del Id

2020-01-24 12:20 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/service/UserService.java
> +        User user= this.userJpaRepository.findById(id)
podrias reutilizar el metodo findById de esta clase, que ya tira la excepcion

2020-01-24 12:20 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/service/UserService.java
> +        User oldUser= this.userJpaRepository.findById(id)
mismo comment que el delete

2020-01-24 13:18 UTC, ghost requested changes

2020-01-24 13:18 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controller/UserController.java
> +        User user = this.findById(id);
El `findById(id)` ponelo en el service y que llame directamente al repository

2020-01-24 13:18 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controller/UserController.java
> +        User oldUser = this.findById(id);
Lo mismo acá

2020-01-24 13:18 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/service/UserService.java
> +        user.setId(idString);
esto podria estar en una linea: `user.setId(UUID.randomUUID().toString()`

2020-01-24 13:18 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/service/UserService.java
> +        return new UserResponse(idString);
`return new UserResponse(user.getId())`

2020-01-24 14:11 UTC, damiTacconi commented
cuando puedan revisarlo, porque creo que necesito los candidatos para seguir con las elecciones

2020-01-24 14:41 UTC, ghost approved these changes

2020-01-24 14:42 UTC, merged