Feature get election results
MoyaFausto/Challenge-Elections-Dami pull request #4
Opened 2020-01-28 13:15 UTC by damiTacconi

2020-01-28 15:54 UTC, ghost requested changes

2020-01-28 15:54 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/service/VoteService.java
> +                .reduce(0, Integer::sum);
Esto no lo podes sacar haciendo `election.length()`?

2020-01-28 17:32 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/controller/ElectionController.java
> +       return this.voteService.getElectionResult(id_election);
dale un espacio antes del return asi se ve mas facil

2020-01-28 17:32 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/entities/CandidateVotes.java
> +@ToString
ya con data te da el tostring

2020-01-28 17:32 UTC, MatiasTassara commented on src/main/java/net/avalith/elections/service/VoteService.java
> +                    return CandidateVotes.builder()
esto quedaria mejor en una funcion aparte y la llamas desde aca, para que no quede tanto choclo

2020-01-29 19:40 UTC, ghost requested changes

2020-01-29 19:40 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/controller/ElectionController.java
> +        this.electionHistoryService.generateHistory(this.findAll());
Acá estas trayendo todos los registros desde base de datos, podrias armarte una query custom que traiga solo las elecciones activas

2020-01-29 19:40 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/entities/CandidateVoteRequest.java
>      private Integer candidate_id;
Ponerlo en `camelCase` y para que salga en `snake_case` en el postman usar `@JsonProperty("snake_case")`

2020-01-29 19:40 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/entities/CandidateVotes.java
> +    private Integer votes;
Ponerlo en `camelCase` y para que salga en `snake_case` en el postman usar `@JsonProperty("snake_case")`

2020-01-29 19:40 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/entities/ElectionVotes.java
> +    private Integer id_election;
Ponerlo en `camelCase` y para que salga en `snake_case` en el postman usar `@JsonProperty("snake_case")`

2020-01-29 19:40 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/entities/ElectionVotes.java
> +    private Integer total_votes;
Ponerlo en `camelCase` y para que salga en `snake_case` en el postman usar `@JsonProperty("snake_case")`

2020-01-29 19:40 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/service/ElectionHistoryService.java
> +                .filter(e -> e.getEndDate().isAfter(LocalDateTime.now()))
Ya podria llegarte filtrada desde base de datos

2020-01-29 19:40 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/service/ElectionHistoryService.java
> +        electionVotes.forEach(ev -> {
no podrias poner el forEach despues del map?

2020-01-29 19:40 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/service/UserService.java
> +                        .dni(10000000 + new Random().nextInt(50000000))
Creo que tienen algo tipo el dni en random User

2020-01-29 19:40 UTC, MoyaFausto commented on src/main/java/net/avalith/elections/service/VoteService.java
> +        return CandidateVotes.builder()
Espacio antes del return

2020-01-29 19:40 UTC, MoyaFausto commented on src/main/resources/application.properties
> +history.time=0 0 0/1 * * ?
La idea era poner los milisegundos, pero en cron esta bien tambien.

2020-01-29 19:58 UTC, damiTacconi commented on src/main/java/net/avalith/elections/service/ElectionHistoryService.java
> +                .filter(e -> e.getEndDate().isAfter(LocalDateTime.now()))
deberia haber otro commit donde ya habia hecho ese cambio, ahi hice otro

2020-01-29 19:59 UTC, damiTacconi commented on src/main/java/net/avalith/elections/controller/ElectionController.java
> +        this.electionHistoryService.generateHistory(this.findAll());
claro claro, ya lo cambie, deberia estar otro commit mas actual con el cambio ya hecho.

2020-01-29 20:23 UTC, ghost approved these changes

2020-01-30 15:04 UTC, ghost approved these changes

2020-01-30 15:04 UTC, merged